kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "flutter-web-app" 
spec:
  runPolicy: "Serial" 
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: "flutter-web-app"
    - type: "ImageChange"
  source:
    git:
      uri: "https://github.com/brianorwhatever/flutter-web-app-sample"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "flutter-web-app:latest"

